# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#主食
Freshness.create(name:'米',freshness:31)
Freshness.create(name:'パン',freshness:3)
Freshness.create(name:'うどん',freshness:10)
#肉
Freshness.create(name:'牛肉',freshness:3)
Freshness.create(name:'豚肉',freshness:3)
Freshness.create(name:'米',freshness:2)
#野菜
Freshness.create(name:'トマト',freshness:14)
Freshness.create(name:'きゅうり',freshness:2)
Freshness.create(name:'たまねぎ',freshness:31)
Freshness.create(name:'なす',freshness:2)
Freshness.create(name:'にんじん',freshness:7)
Freshness.create(name:'じゃがいも',freshness:31)
Freshness.create(name:'大根',freshness:10)
Freshness.create(name:'キャベツ',freshness:14)
Freshness.create(name:'レタス',freshness:4)
Freshness.create(name:'ほうれん草',freshness:7)
Freshness.create(name:'ピーマン',freshness:7)
#魚(適当に全部4日にしました)
Freshness.create(name:'さんま',freshness:4)
Freshness.create(name:'あじ',freshness:4)
Freshness.create(name:'マグロ',freshness:4)
Freshness.create(name:'鮭',freshness:4)
Freshness.create(name:'カツオ',freshness:4)
#加工食品(納豆とか)
Freshness.create(name:'納豆',freshness:7)
Freshness.create(name:'豆腐',freshness:7)
Freshness.create(name:'厚揚げ',freshness:3)
Freshness.create(name:'かまぼこ',freshness:10)
Freshness.create(name:'ちくわ',freshness:10)
Freshness.create(name:'はんぺん',freshness:10)
Freshness.create(name:'油揚げ',freshness:7)
Freshness.create(name:'こんにゃく',freshness:31)
#乳製品(謎のチーズ充実)全て開封後
Freshness.create(name:'牛乳',freshness:10)
Freshness.create(name:'カッテージチーズ',freshness:7)
Freshness.create(name:'カマンベールチーズ',freshness:7)
Freshness.create(name:'ゴーダチーズ',freshness:14)
Freshness.create(name:'エダムチーズ',freshness:14)
Freshness.create(name:'ブルーチーズ',freshness:10)
Freshness.create(name:'モッツァレラチーズ',freshness:2)
Freshness.create(name:'粉チーズ',freshness:31)
Freshness.create(name:'バター',freshness:31)
Freshness.create(name:'マーガリン',freshness:31)
Freshness.create(name:'ヨーグルト',freshness:3)
#果物
Freshness.create(name:'バナナ',freshness:7)
Freshness.create(name:'りんご',freshness:31)
Freshness.create(name:'いちご',freshness:4)
Freshness.create(name:'みかん',freshness:7)
Freshness.create(name:'ぶどう',freshness:14)
Freshness.create(name:'キウィ',freshness:7)
#調味料(全て開封済み)
Freshness.create(name:'マヨネーズ',freshness:31)
Freshness.create(name:'ケチャップ',freshness:31)
Freshness.create(name:'しょうゆ',freshness:365)
Freshness.create(name:'みそ',freshness:62)